[package]
name = "sawa-infra-memory"
version = "0.1.0"
edition.workspace = true

[dependencies]
sawa-core.workspace = true
chrono.workspace = true
uuid.workspace = true

[dev-dependencies]
sawa-repository-tests.workspace = true
