[workspace]
resolver = "2"
members = ["bin/*", "crates/*"]

[workspace.package]
edition = "2024"

[workspace.dependencies]
sawa-core = { path = "crates/core" }
sawa-infra-memory = { path = "crates/infra-memory" }
