[package]
name = "sawa-repository-tests"
version = "0.1.0"
edition.workspace = true

[dependencies]
sawa-core.workspace = true
chrono = "0.4"
uuid = "1"
url.workspace = true
iso_currency = "0.5.3"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
