[package]
name = "sawa-repository-tests"
version = "0.1.0"
edition.workspace = true

[dependencies]
sawa-core.workspace = true
chrono.workspace = true
uuid.workspace = true
url.workspace = true
tokio.workspace = true
