[package]
name = "sawa-core"
version = "0.1.0"
edition.workspace = true

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
iso_currency = "0.5.3"
thiserror = "2.0.17"
url.workspace = true
uuid = { version = "1", features = ["v7"] }
