[package]
name = "sawa-core"
version = "0.1.0"
edition.workspace = true

[dependencies]
url.workspace = true
chrono.workspace = true
uuid.workspace = true
thiserror.workspace = true
serde.workspace = true

iso_currency = "0.5.3"
