[package]
name = "sawa"
version = "0.1.0"
edition.workspace = true

[dependencies]
tokio.workspace = true
tower-http.workspace = true
axum.workspace = true
sawa-api.workspace = true
sawa-application.workspace = true
sawa-infra-memory.workspace = true
tower = "0.5"
tracing-subscriber = "0.3"

tower-sessions-sqlx-store = { version = "0.15.0", features = ["postgres"] }
tower-sessions-memory-store = "0.14.0"
