[package]
name = "sawa"
version = "0.1.0"
edition.workspace = true

[dependencies]
tokio.workspace = true
tower-http.workspace = true
axum.workspace = true
sawa-api.workspace = true
sawa-application.workspace = true
sawa-infra-memory.workspace = true
tower = "0.4"
tracing-subscriber = "0.3"
